// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noqnlxtxvrqjrdbiatqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcW5seHR4dnJxanJkYmlhdHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTY2NTgsImV4cCI6MjA1Nzg3MjY1OH0.c2gy7Q4HGn09Pdx6jdvUsP4HKnwrRWBNEruRuzJIRng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);